### PR TITLE
integrated additional classifiers for model comparison along with doc…

### PR DESCRIPTION
**Pull request by MJakash**
This pull request implements a machine learning pipeline for resume classification using three classifiers: Support Vector Machine (SVM), Random Forest, and XGBoost. The pipeline includes data preprocessing, skill extraction from resumes, and model evaluation using accuracy, recall, precision, and F1 score metrics.

The results demonstrate the Random Forest classifier as the best performer in cross-validation, while SVM achieved the highest precision on the test set. This work lays the foundation for further enhancements in resume classification and skill extraction methodologies.

### CODE REVIEW

**Comment by eashwar05** [comment]
change code to handle zero division warning while cross validating and evaluvating model

**Comment by MJakash** [comment]
Fixed!

**Comment by eashwar05** [comment]
just remove the line where you import pdfminer.six and in line 226 change clf to rf_clf 
and i think it's good to go

**Comment by MJakash** [comment]
Fixed!

**Comment by eashwar05** [comment]
it seems like the latest commit is not part of this branch, so i can't merge the pull request
can you fix it

**Comment by MJakash** [comment]
I fixed all the issues with a new pull request, can u please proceed
further?

**Pull request closed without merging**
